# Generated by Django 3.0.6 on 2020-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('crop1', models.CharField(max_length=50)),
                ('crop2', models.CharField(max_length=50)),
                ('crop3', models.CharField(max_length=50)),
                ('crop4', models.CharField(max_length=50)),
                ('crop5', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
