# Generated by Django 3.0.6 on 2020-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='contact',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
