# Generated by Django 3.0.6 on 2020-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_farmers', '0003_remove_farmers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='password',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
