# Generated by Django 3.0.6 on 2020-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_farmers', '0004_farmers_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
